### ISSUE TITLE
Search broken

### ISSUE THREAD

**Issue by Nebelung-Dev** [titaniumnetwork-dev/Vanadium#5]
When you enter a url it returns an error. Try making it go to https://example.com/prefix/gateway?url=https://example.com

**Comment by nullnvoid1** [comment]
visiting urls within the proxy does not appear to be broken on any of my test instances; can you ensure your copy of the repository is up to date with all npm packages installed?

**Comment by Nebelung-Dev** [comment]
here is my demo site: https://vanadium.nebelung.repl.co
when I type in https://google.com it goes to https://vanadium.nebelung.repl.co/search/hvtrs8/-wuw,gmoelg.aoo/
i should go to https://vanadium.nebelung.repl.co/search/gateway?url=google.com

**Comment by nullnvoid1** [comment]
The encoded URLs are there by design, to avoid web-filters flagging the URLs being visited by checking for keywords.

Your demo site appears to be working properly.

**Comment by Nebelung-Dev** [comment]
ok
